# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Detective Box API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create env file
      run: |
        echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "ADMIN_TOKEN=${{ secrets.ADMIN_TOKEN }}" >> .env
        echo "AWS_ENDPOINT_URL=${{ secrets.AWS_ENDPOINT_URL }}" >> .env
        echo "AWS_KEY_ID=${{ secrets.AWS_KEY_ID }}" >> .env
        echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
        echo "AWS_BUCKET=${{ secrets.AWS_BUCKET }}" >> .env
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v3
      with:
        name: production-files
        path: .


  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: production-files
          path: .
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/data/detective-box/api"

  migrate:
    name: Database migration
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Execute migration
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ secrets.DB_MIGRATE_URL }}'
          method: 'POST'
          customHeaders: '{"Authorization": "Bearer ${{ secrets.ADMIN_TOKEN }}"}'
